global:
  scrape_interval: 2s  # <--- 여기를 15s(기본값)에서 2s~5s로 변경!
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'kafka-lag-exporter'
    static_configs:
      - targets: ['kafka-lag-exporter:8000']
        labels:
          env: 'dev'

  - job_name: 'kafka-broker'
    static_configs:
      - targets: ['kafka-1:9404', 'kafka-2:9405', 'kafka-3:9406']
        labels:
          env: 'dev'